version: "3.7"
services:
  twikwak17:
    image: shaypal5/twikwak17:latest
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    ports:
      - "8888"
      - "6006"
    volumes:
      - type: bind
        source: /home/shaypalachy/Dropbox/data/twitter7
        target: /root/data/twitter7
      - type: bind
        source: /home/shaypalachy/Dropbox/data/kwak10www
        target: /root/data/kwak10www
      - type: bind
        source: /home/shaypalachy/Dropbox/data/twikwak17
        target: /root/data/twikwak17
